config/routes.rb
Rails.application.routes.draw do
# pour la resource slides sur le frontend,
# on autorise que la vue index
# les autres vues ne seront pas utilisées
  resources :slides, only: [:index]

  # on crée un namespace admin pour administrer les slides
  namespace :admin do
    resources :slides

    # On ajoute un root dans le namespace pour que
    # http://localhost:3000/admin
    # charge par défaut
    # http://localhost:3000/admin/sliders
    # l'url dans la barre d'adresse restera
    # http://localhost:3000/admin
    root 'slides#index'
  end

  # On crée là aussi un root pour que
  # http://localhost:3000
  # charge http://localhost:3000/sliders
  # l'url dans la barre d'adresse restera
  # http://localhost:3000/

  root 'slides#index'
end

app/models/slide.rb
class Slide < ActiveRecord::Base

  # spécifie que paperclip aura a géré :picture
  # que le fichier original sera redimensionné en 1920x1800
  # et que thumb sere redimensionné en 200x200
  # si le fichier ne devait pas être présent c'est
  # le fichiers missing.png qui sera affiché dans les 2 dimensions

  has_attached_file :picture, styles: { original: "1920x1800>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"

  # on s'assure que le fichier envoyé sera de type 'image'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  # On vérifie que le fichier aura l'extension 'png', 'jpg', 'jpeg'
  validates_attachment_file_name :picture, matches: [/png\Z/, /jpe?g\Z/]

  # On vérifie que l'image envoyé ne fasse pas plus d'un 1M
  validates_with AttachmentSizeValidator, attributes: :picture, less_than: 1.megabytes

  # on vérifie que les 4 champs seront bien rempli
  validates :name, :desc, :author, :picture, presence: true

  # on crée 2 scopes pour simplifier la synthaxe du controller
  # on recherche que les publication à 'true'
  scope :publication, -> { where(published: true) }
  # on cherche les publications dont la date du jour est comprise dans les dates de publication
  scope :min_publication, -> { where('DateTime(published_from) < ? ', DateTime.now ) }
  scope :max_publication, -> { where('DateTime(published_to) > ?', DateTime.now ) }
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to admin_slides_path, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to  admin_slides_path, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to admin_slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :desc, :author, :picture, :published, :published_from, :published_to)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController

  # GET /slides
  # GET /slides.json
  def index
    # requete de base que l'on va passer au model
    # @slides = Slide.where("DateTime(published_from) < ? AND DateTime(published_to) > ? AND published == ?", DateTime.now, DateTime.now, true)

    # Grace au scope créé dans le model on simplifie la lecture du code
    @slides = Slide.publication.min_publication.max_publication
  end
end

app/helpers/admin/slides_helper.rb
module Admin::SlidesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/slides/_form.html.erb
<%= form_for([:admin,@slide], html: { multipart: true }) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :published_from %><br>
    <%= f.date_field :published_from %>
  </div>
  <div class="field">
    <%= f.label :published_to %><br>
    <%= f.date_field :published_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/slides/edit.html.erb
<h1>Editing Slide</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_slides_path(@slide) %> |
<%= link_to 'Back', admin_slides_path %>

app/views/admin/slides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Slides</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Name</th>
      <th>Desc</th>
      <th>Author</th>
      <th>Published</th>
      <th>Published_from</th>
      <th>Published_to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= image_tag slide.picture.url(:thumb) %></td>
        <td><%= slide.name %></td>
        <td><%= slide.desc.html_safe %></td>
        <td><%= slide.author.html_safe %></td>
        <td><%= slide.published %></td>
        <td><%= slide.published_from %></td>
        <td><%= slide.published_to %></td>
        <td><%= link_to 'Show', admin_slide_path(slide) %></td>
        <td><%= link_to 'Edit', edit_admin_slide_path(slide) %></td>
        <td><%= link_to 'Destroy', admin_slide_path(slide), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_admin_slide_path %>

app/views/admin/slides/new.html.erb
<h1>New Slide</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_slides_path %>

app/views/admin/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @slide.desc %>
</p>

<p>
  <strong>Author:</strong>
  <%= @slide.author %>
</p>

<%= link_to 'Edit', edit_admin_slide_path(@slide) %> |
<%= link_to 'Back', admin_slides_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysliders</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/slides/index.html.erb
<div class="slides">
  <% @slides.each do |slide| %>
    <div class="slide">
      <p>
        <%= slide.desc %>
      </p>
      <p>
        <%= slide.author %>
      </p>
      <p>
        <%= image_tag slide.picture.url %>
      </p>
    </div>
  <% end %>
</div>